# serverless.yml

service: aws-serverless-express-application

provider:
  name: aws
  runtime: nodejs10.x
  stage: stg
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: id2
            AttributeType: S

        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: id2
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: DynamoTableTempName
